### ISSUE TITLE
Setup Clarification

### ISSUE THREAD

**Issue by bfdill** [jalexanderfox/dotfiles#1]
Hi, thanks for the repo.

The setup shows commands executed using a fully qualified path, but it seems as though you need to be in the ~/.dotfiles directory because setup.sh uses relative pathing.

Maybe changing things like:
```bash
~/.dotfiles/setup.sh brew fresh cask
```
to
```bash
cd ~/.dotfiles && ./setup.sh brew fresh cask
```

**Comment by jalexanderfox** [comment]
Thanks @bfdill, I updated the readme.md to reflect your suggestion.
